# This workflow will build a package using Gradle and then publish it to Bintray packages when a release is created
name: Gradle Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      run: gradle build

    - name: Publish to Bintray
      run: gradle publish
      env:
        bintrayKey: ${{ secrets.BINTRAY_KEY }}
